# Generated by Django 5.0.6 on 2024-06-18 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('rok', models.PositiveIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kategoria', models.CharField(max_length=100)),
                ('miejsce_przechowywania', models.CharField(max_length=200)),
                ('liczba_egz', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaZmian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia_zmian', to='archiwum.dokument')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
