# Generated by Django 5.0.6 on 2024-06-19 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiwum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiazmian',
            name='data_wypozyczenia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiazmian',
            name='data_zwrotu',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiazmian',
            name='wypozyczony',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historiazmian',
            name='dokument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiwum.dokument'),
        ),
    ]
